# Generated by Django 5.2.7 on 2025-11-03 03:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0006_year'),
        ('docs_type', '0003_copy_name_to_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, default=None, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=10)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('total_versions', models.IntegerField(default=1)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_format', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document (.doc)'), ('docx', 'Word Document (.docx)'), ('txt', 'Text File')], default='pdf', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('publisher_id', models.CharField(blank=True, help_text='User ID or username', max_length=255, null=True)),
                ('publisher_name', models.CharField(blank=True, default='N/A', help_text='Human readable publisher name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_vector_processed', models.BooleanField(default=False, help_text='Indicates if the document has been processed for vector DB')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='document.document')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs_type.documenttype')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'permissions': [('can_view_document', 'Can view Document'), ('can_download_document', 'Can download Document'), ('can_upload_document', 'Can upload Document'), {'Can search Document', 'can_search_document'}],
            },
        ),
    ]







