# Generated by Django 5.2.7 on 2025-11-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_document', 'Can view Document'), ('can_download_document', 'Can download Document'), ('can_upload_document', 'Can upload Document'), ('can_search_document', 'Can search Document')]},
        ),
    ]







