# Generated by Django 5.2.7 on 2025-12-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_document', 'Can view Document'), ('can_download_document', 'Can download Document'), ('can_upload_document', 'Can upload Document'), {'Can search Document', 'can_search_document'}]},
        ),
    ]







