# Generated by Django 5.2.7 on 2025-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_preview_path',
            field=models.CharField(blank=True, help_text='Path to auto-generated PDF preview for DOCX/XLSX/PPTX', max_length=500, null=True),
        ),
    ]







