# Generated by Django 5.2.7 on 2025-12-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_add_pdf_preview_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pdf_preview_path',
        ),
    ]







