# Generated by Django 5.2.7 on 2026-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0009_alter_documentindexingjob_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentindexingjob",
            name="stage",
            field=models.TextField(
                choices=[
                    ("queued", "Queued"),
                    ("deactivating_previous_versions", "Deactivating Previous Versions"),
                    ("extracting", "Extracting"),
                    ("indexing", "Indexing"),
                    ("finalizing", "Finalizing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="queued",
            ),
        ),
    ]
