"""
Custom exception handler for Django REST Framework.
Handles UnreadablePostError and other connection-related errors.
"""

from rest_framework.views import exception_handler
from rest_framework.response import Response
from rest_framework import status
import logging

logger = logging.getLogger(__name__)

def custom_exception_handler(exc, context):
    """
    Custom exception handler that catches UnreadablePostError
    and returns a proper error response.
    """
    # Call REST framework's default exception handler first
    response = exception_handler(exc, context)
    
    # If no response was generated by the default handler,
    # check if this is an UnreadablePostError
    if response is None:
        from django.http.request import UnreadablePostError
        
        if isinstance(exc, UnreadablePostError):
            logger.error(f"Connection reset during upload: {exc}")
            
            # Check if this is an upload endpoint
            request = context.get('request')
            if request and request.path.startswith('/api/documents/upload'):
                return Response({
                    'status': 'error',
                    'status_code': 400,
                    'message': 'Upload failed due to connection issue. Please try again.',
                    'data': {
                        'error': 'Connection reset during upload',
                        'hint': 'This usually happens when the connection is lost during large file upload. Try uploading a smaller file or check your network connection.'
                    }
                }, status=status.HTTP_400_BAD_REQUEST)
            
            # For other endpoints, log the error but let Django handle it
            logger.warning(f"Connection reset on non-upload endpoint {request.path if request else 'unknown'}: {exc}")
    
    return response