# Generated by Django 5.2.3 on 2025-06-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinput',
            name='keycloak_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='keycloak_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]







