# Generated by Django 5.2.5 on 2025-08-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatsession_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinput',
            name='keycloak_sub',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='keycloak_sub',
        ),
    ]







