# Generated by Django 5.2.6 on 2025-10-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chatinput_keycloak_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when session was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - session remains viewable but not editable'),
        ),
    ]







