# Generated by Django 5.2.7 on 2025-10-31 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsession_deleted_at_chatsession_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='is_deleted',
        ),
    ]







