# Generated by Django 5.2.7 on 2025-12-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatmessage_chat_messag_session_16632f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_messag_session_16632f_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_messag_session_d003e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_messag_created_eb4133_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_user_id_c65971_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chat_sessio_created_d061d1_idx',
        ),
    ]







