# Generated by Django 5.2.7 on 2026-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_chatmessage_chat_messag_session_16632f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='document_references',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
