# Generated by Django 5.2.7 on 2026-02-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatmessage_document_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
