# Generated by Django 5.2.7 on 2026-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_messagefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefeedback',
            name='message_id_str',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
