# Generated by Django 5.2.5 on 2025-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('user', 'User'), ('userdownload', 'Userdownload')], default='user', max_length=20),
        ),
    ]
