# Generated by Django 5.2.5 on 2025-08-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ldap_user',
            field=models.BooleanField(default=False),
        ),
    ]
