# Generated by Django 5.2.5 on 2025-08-26 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_ldap_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Username may only contain letters, numbers, underscores, and dots.', regex='^[a-zA-Z0-9_.]+$')]),
        ),
    ]
