# Generated by Django 5.2.7 on 2025-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    app_label = 'user'
    dependencies = [
        ('user', '0007_alter_user_is_ldap_user_user_users_email_4b85f2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_employe_55e465_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_ldap_c77f06_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_created_6541e9_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ldap_user',
            field=models.BooleanField(default=False),
        ),
    ]
