# Generated by Django 5.2.7 on 2026-03-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_add_language_and_avatar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_ldap_groups",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="last_ldap_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
