# Generated by Django 5.2.7 on 2026-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_last_ldap_login_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LDAPGroupRoleMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ldap_group_name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No automatic role"),
                            ("SuperAdmin", "SuperAdmin"),
                            ("Admin", "Admin"),
                            ("User", "User"),
                            ("UserDownload", "UserDownload"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LDAP Group Mapping",
                "verbose_name_plural": "LDAP Group Mappings",
                "db_table": "ldap_group_role_mappings",
                "ordering": ["ldap_group_name"],
            },
        ),
    ]
