# Generated by Django 5.2.5 on 2025-08-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='presentation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]







