# Generated by Django 5.2.7 on 2025-10-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]







