# Generated by Django 5.2.7 on 2025-11-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]







