# Generated by Django 5.2.6 on 2025-11-02 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_delete_year'),
    ]

    operations = [
        # Skip creating the table since it already exists in the database
        # The years table was created manually or by a previous migration
        migrations.RunSQL(
            sql="SELECT 1",  # No-op SQL to satisfy migration requirements
            reverse_sql="SELECT 1"
        ),
    ]







